---
title: "Graphing with ggplot"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(ggplot2)
```

```{r}
# Load the mpg dataset
data('mpg')
mpgData = mpg

# Print the first five rows (or samples) in the data frame
head(mpgData, 5)
str(mpgData)
```

```{r}
foodData = read.csv('DataSets/food-texture.csv',header = TRUE, row.names = 1,stringsAsFactors = TRUE)
head(foodData,5)
str(foodData)
```


```{r}
#Add another column dataframe called Taste

#foodData['Taste']=sample(c('poor','fair','good','very good'),replace = TRUE, nrow(foodData),p=c(0.25,0.25,0.25,0.25))
```

```{r}
#write.csv(foodData, 'DataSets/food-texture.csv')
```

```{r}
continuous_cols = c( 'Oil','Density', 'Fracture' ,'Hardness')
continuous_cols
catergorical_cols = c('Crispy', 'Taste')
catergorical_cols
```

```{r}
#Convert categorical columns to factor type
foodData[catergorical_cols] = lapply(foodData[catergorical_cols], factor)
str(foodData)
```

```{r}
p = ggplot(data = foodData) + geom_point(aes(x = Oil, y = Density))
p
```


```{r}
p = ggplot(data = foodData) + geom_point(aes(x = Oil, y = Density, color = Crispy))
p
```

```{r}
p = ggplot(data = foodData) + geom_boxplot(aes(x = Crispy, y = Density, color = Crispy))
p
```

```{r}
median(density10)
density10 <= median(density10)
sum(density10 <= median(density10))
mean(density10 <= median(density10))

sum(density10 <= median(density10))*100
mean(density10 <= median(density10))*10
```


```{r}
quantile(density10, 0.25)
quantile(density10, 0.75)-quantile(density10,0.25)

density13 = foodData[foodData['Crispy'] ==13,]$Density
density13
quantile(density13, 0.75)-quantile(density13,0.25)
```

```{r}
p = ggplot(data = foodData) + geom_histogram(aes(x= Density),binwidth = 100, color = 'blue')
p
```

```{r}
p = ggplot(data = foodData[foodData$Crispy==13,]) + geom_histogram(aes(x= Density),binwidth = 100, color = 'blue')
p
```



```{r}
# Initiate the ggplot() function binding to the car data frame
ggplot(data = mpgData)

# Create a plot object
p1 = ggplot(data = mpgData)

# Use the aes() function to specify the aesthetic mapping, that is, which variables
# should be plotted
p1 = ggplot(data = mpgData, aes(x = disp, y = hwy))

# Use the geom_ type functions to add geometric elements
p1 = ggplot(data = mpgData, aes(x = displ, y = hwy)) +
  geom_point()

# Add labels and title
p1 = p1 + labs(x = 'Displacement (litres)', y = 'Mileage (MPG)', title = 'Mileage vs. Displacement')
p1
```


```{r}
# Map aesthetics to variables

# Map the color aesthetic to the class variable
p2 = ggplot(data = mpgData) +
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
p2
```

```{r}
# Map aesthetics to variables

# Map the size (or alpha or shape) aesthetic to the class variable
p3 = ggplot(data = mpgData) +
  geom_point(aes(x = displ, y = hwy, color = class, shape = drv)) + labs(x = 'Displacement (litres)', y = 'Mileage (MPG)', title = 'Mileage vs. Displacement')
p3
```

```{r}
# Set aesthetic manually

# Mark the points blue in color, square in shape, and fixed size
p4 = ggplot(data = mpgData) +
  geom_point(aes(x = displ, y = hwy), color = 'red', size = 1) + labs(x = 'Displacement (litres)', y = 'Mileage (MPG)', title = 'Mileage vs. Displacement')
p4
```

```{r}
# How do we relate a continuous and a categorical feature?
p5 = ggplot(data = mpgData) + 
  geom_boxplot(aes(x = class, y = hwy)) + labs(x = 'Vehicle Class', y = 'Mileage (MPG)', title = 'Mileage vs. Vehicle Class')
p5
```


```{r}
# Add additional variables using facets

# Plot mileage w.r.t. each class individually
ggplot(data = mpgData) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(, nrow = 2)
```

```{r}
# Plot mileage w.r.t drive train and number of cylinders
ggplot(data = mpgData) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid()
```

```{r}
# A quick exercise on facet plotting with filtering of samples
# Investigate the number of levels in the cyl feature
factor()

# How many cars of each cyl type are there?
mpgData %>% 

# Filter samples with 3 and 5 cylinder cars (which are very rare)
# mpgData = mpgData %>% filter(!(? %in% c(?, ?)))
# 
# head(mpgData, 5)
# 
# # Map the color aesthetic to the cyl variable
# p5 = ggplot(data = mpgData) +
#   geom_point(mapping = aes(x = displ, y = hwy))
# p5
```


